FROM ubuntu:22.04
ARG TARGETARCH
RUN sed -i "s@http://.*archive.ubuntu.com@http://mirrors.cqu.edu.cn@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@http://mirrors.cqu.edu.cn@g" /etc/apt/sources.list
RUN mkdir /spkdfs && mkdir /spkdfs/bin && mkdir /spkdfs/data && mkdir /spkdfs/logs && mkdir /spkdfs/coredumps
COPY ./build/amd64/node /spkdfs/bin/node
ENTRYPOINT ["/spkdfs/bin/node"]