version: '3.7'

services:
  node1:
    image: spkdfs:latest
    command: ["-nodes=192.168.88.101,192.168.88.102,192.168.88.103", "-nn_port=8000", "-dn_port=8001", "-data_path=/spkdfs/data", "-log_dir=/spkdfs/logs", "-expected_nn=3"]
    volumes:
      - ./tmp/spkdfs_1/data:/spkdfs/data
      - ./tmp/spkdfs_1/logs:/spkdfs/logs
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.101

  node2:
    image: spkdfs:latest
    command: ["-nodes=192.168.88.101,192.168.88.102,192.168.88.103", "-nn_port=8000", "-dn_port=8001", "-data_path=/spkdfs/data", "-log_dir=/spkdfs/logs", "-expected_nn=3"]
    volumes:
      - ./tmp/spkdfs_2/data:/spkdfs/data
      - ./tmp/spkdfs_2/logs:/spkdfs/logs
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.102

  node3:
    image: spkdfs:latest
    command: ["-nodes=192.168.88.101,192.168.88.102,192.168.88.103", "-nn_port=8000", "-dn_port=8001", "-data_path=/spkdfs/data", "-log_dir=/spkdfs/logs", "-expected_nn=3"]
    volumes:
      - ./tmp/spkdfs_3/data:/spkdfs/data
      - ./tmp/spkdfs_3/logs:/spkdfs/logs
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.103

  node4:
    image: spkdfs:latest
    command: ["-nodes=192.168.88.101,192.168.88.102,192.168.88.103", "-nn_port=8000", "-dn_port=8001", "-data_path=/spkdfs/data", "-log_dir=/spkdfs/logs", "-expected_nn=3"]
    volumes:
      - ./tmp/spkdfs_4/data:/spkdfs/data
      - ./tmp/spkdfs_4/logs:/spkdfs/logs
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.104

  node5:
    image: spkdfs:latest
    command: ["-nodes=192.168.88.101,192.168.88.102,192.168.88.103", "-nn_port=8000", "-dn_port=8001", "-data_path=/spkdfs/data", "-log_dir=/spkdfs/logs", "-expected_nn=3"]
    volumes:
      - ./tmp/spkdfs_5/data:/spkdfs/data
      - ./tmp/spkdfs_5/logs:/spkdfs/logs
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.105

networks:
  spkdfs_net:
    ipam:
      config:
        - subnet: 192.168.88.0/24
