version: '3.7'

services:
  node1:
    image: spkdfs:latest
    command:
      [
        "-nodes=192.168.88.101,192.168.88.102,192.168.88.103,192.168.88.104,192.168.88.105",
        "-nn_port=8000",
        "-dn_port=8001",
        "-data_dir=/spkdfs/data",
        "-log_dir=/spkdfs/logs",
        "-coredumps_dir=/spkdfs/coredumps",
        "-expected_nn=3"
      ]
    volumes:
      - ./tmp/spkdfs_1/data:/spkdfs/data
      - ./tmp/spkdfs_1/coredumps:/spkdfs/coredumps
      - ./tmp/spkdfs_1/logs:/spkdfs/logs
    ports:
      - "18000:8000"
      - "18001:8001"
      - "13000:3000"
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.101

  node2:
    image: spkdfs:latest
    # entrypoint: "gdbserver :23000 /spkdfs/bin/node"
    command:
      [
        "-nodes=192.168.88.101,192.168.88.102,192.168.88.103,192.168.88.104,192.168.88.105",
        "-nn_port=8000",
        "-dn_port=8001",
        "-data_dir=/spkdfs/data",
        "-log_dir=/spkdfs/logs",
        "-coredumps_dir=/spkdfs/coredumps",
        "-expected_nn=3"
      ]
    volumes:
      - ./tmp/spkdfs_2/data:/spkdfs/data
      - ./tmp/spkdfs_2/coredumps:/spkdfs/coredumps
      - ./tmp/spkdfs_2/logs:/spkdfs/logs
    ports:
      - "28000:8000"
      - "28001:8001"
      - "23000:3000"
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.102

  node3:
    image: spkdfs:latest
    command:
      [
        "-nodes=192.168.88.101,192.168.88.102,192.168.88.103,192.168.88.104,192.168.88.105",
        "-nn_port=8000",
        "-dn_port=8001",
        "-data_dir=/spkdfs/data",
        "-log_dir=/spkdfs/logs",
        "-coredumps_dir=/spkdfs/coredumps",
        "-expected_nn=3"
      ]
    volumes:
      - ./tmp/spkdfs_3/data:/spkdfs/data
      - ./tmp/spkdfs_3/coredumps:/spkdfs/coredumps
      - ./tmp/spkdfs_3/logs:/spkdfs/logs
    ports:
      - "38000:8000"
      - "38001:8001"
      - "33000:3000"
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.103

  node4:
    image: spkdfs:latest
    command:
      [
        "-nodes=192.168.88.101,192.168.88.102,192.168.88.103,192.168.88.104,192.168.88.105",
        "-nn_port=8000",
        "-dn_port=8001",
        "-data_dir=/spkdfs/data",
        "-log_dir=/spkdfs/logs",
        "-coredumps_dir=/spkdfs/coredumps",
        "-expected_nn=3"
      ]
    volumes:
      - ./tmp/spkdfs_4/data:/spkdfs/data
      - ./tmp/spkdfs_4/coredumps:/spkdfs/coredumps
      - ./tmp/spkdfs_4/logs:/spkdfs/logs
    ports:
      - "48000:8000"
      - "48001:8001"
      - "43000:3000"
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.104

  node5:
    image: spkdfs:latest
    command:
      [
        "-nodes=192.168.88.101,192.168.88.102,192.168.88.103,192.168.88.104,192.168.88.105",
        "-nn_port=8000",
        "-dn_port=8001",
        "-data_dir=/spkdfs/data",
        "-log_dir=/spkdfs/logs",
        "-coredumps_dir=/spkdfs/coredumps",
        "-expected_nn=3"
      ]
    volumes:
      - ./tmp/spkdfs_5/data:/spkdfs/data
      - ./tmp/spkdfs_5/coredumps:/spkdfs/coredumps
      - ./tmp/spkdfs_5/logs:/spkdfs/logs
    ports:
      - "58000:8000"
      - "58001:8001"
      - "53000:3000"
    networks:
      spkdfs_net:
        ipv4_address: 192.168.88.105

networks:
  spkdfs_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1
