name: spkdfs-builder

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker image tag'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Aliyun Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfiles/Dockerfile.builder
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.ALIYUN_REGISTRY }}/little_bee/spkdfs_builder:${{ github.event.inputs.tag }}
